name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Babashka - A Clojure babushka for the grey areas of Bash.
      uses: turtlequeue/setup-babashka@v1.5.0
      with:
        babashka-version: 1.3.182

    - name: Run
      env:
        AMOUNT: ${{ env.AMOUNT }}
        HOSTNAME: ${{ env.HOSTNAME }}
        PORT: ${{ env.PORT }}
      run: make run
